name: Intializing Database

on:
  workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  init-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: nikhil74589/Banking-App-2-Tier
          ref: main

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::127348474924:role/github-action-deploy-role
          aws-region: us-east-2

      - name: Upload file on S3
        run: |
          aws s3 mb s3://127348474924-devops-scripts --region us-east-2 2>/dev/null || true
          aws s3 cp init.sql s3://720800607391-devops-scripts/init.sql 
          aws s3 cp init.py s3://720800607391-devops-scripts/init.py 
          echo "✅ Files Uploaded to bucket.."
